#!/bin/sh

VERSION="${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}"
REPOSITORY="uwas-${CI_COMMIT_BRANCH}"

echo $CONTAINER_REGISTRY_PASSWORD | docker login $CONTAINER_REGISTRY -u $CONTAINER_REGISTRY_USER --password-stdin
docker pull $CONTAINER_REGISTRY/$REPOSITORY/$IMAGE_NAME:latest

docker run --rm -e ENVIRONMENT=$QA_ENVIRONMENT -e DRIVER=$WEB_DRIVER -v $PWD:/app $CONTAINER_REGISTRY/$REPOSITORY/$IMAGE_NAME:latest
